
console.log(new Date())
try {
    const number = 2;
    const number = 5;
}
catch (err) {
    console.log(err)
}
finally(
    console.log("tanim")
)